webUI/coral/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'coral.views.home', name='home'),
    # url(r'^coral/', include('coral.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    #url(r'^$', include('hmmer.urls')),
    url(r'', include('hmmer.urls')),
)

webUI/hmmer/urls.py
'''
Created on Jul 8, 2013

@author: taylorak
'''
from django.conf.urls import patterns, url
urlpatterns = patterns('',
    url(r'^$', 'hmmer.views.inputFormDisplay', name="form"),
    url(r'^error/$', 'hmmer.views.errorPage', name="error"),

    # index
    url(r'^(?P<id>\d+\.\d+\.\d+)/$', 'hmmer.views.index', name="index"),

    #clades
    url(r'^(?P<id>\d+\.\d+\.\d+)/clades$', 'hmmer.views.clades', name="clades"),

    #subtypes
    url(r'^(?P<id>\d+\.\d+\.\d+)/unique$', 'hmmer.views.unique', name="unique"),
    url(r'^(?P<id>\d+\.\d+\.\d+)/shortnew$', 'hmmer.views.shortnew', name="shortnew"),
    url(r'^(?P<id>\d+\.\d+\.\d+)/perfect$', 'hmmer.views.perfect', name="perfect"),
    #url(r'^(?P<id>\d+\.\d+\.\d+)/subtypes$', 'hmmer.views.subtypes', name="subtypes"),

    # multiples
    url(r'^(?P<id>\d+\.\d+\.\d+)/multiples/(?P<file>[A-I])/corrected$', 'hmmer.views.multiplesCorrected', name="corrected"),
    url(r'^(?P<id>\d+\.\d+\.\d+)/multiples/(?P<file>[A-I])/resolved$', 'hmmer.views.multiplesResolved', name="resolved"),

    # tree
    url(r'^(?P<id>\d+\.\d+\.\d+)/placementTree/(?P<file>[A-I])/$', 'hmmer.views.tree', name="tree"),

    # chart
    url(r'^(?P<id>\d+\.\d+\.\d+)/(?P<site>[A-Za-z]+\d+)/$', 'hmmer.views.chart', name="chart"),

    # stats                       
    url(r'^(?P<uid>\d+\.\d+\.\d+)/stats/', 'hmmer.views.descriptiveStats', name = 'descStats'),

    #biom sample sunbursts
    url(r'^(?P<uid>\d+\.\d+\.\d+)/(?P<sample>[^/]+)/biom/$', 'hmmer.views.biomGraph', name="biomburst"),
    url(r'^(?P<uid>\d+\.\d+\.\d+)/(?P<sampleA>[^/]+)/(?P<sampleB>[^/]+)/biom/sxs/$', 'hmmer.views.biomGraphSXS',{'template':"biom_graph_sxs.html"},  name="biomburst_sxs"),
    url(r'^json/biom/burst/(?P<uid>\d+\.\d+\.\d+)/(?P<sample>[^/]+)/', 'hmmer.views.generateBiomSampleGraph', name = 'json_biomburst'),
    #############
    # DOWNLOADS #
    #############

    # clades
    url(r'^(?P<id>\d+\.\d+\.\d+)/dlClades/$', 'hmmer.views.dlClades', name="dlClades"),
    url(r'^(?P<id>\d+\.\d+\.\d+)/dlAll/$', 'hmmer.views.dlAll', name="dlAll"),
    url(r'^(?P<id>\d+\.\d+\.\d+)/dlDetailed/$', 'hmmer.views.dlDetailed', name="dlDetailed"),

    # subtypes
    url(r'^(?P<id>\d+\.\d+\.\d+)/dlSubtypes/$', 'hmmer.views.dlSubtypes', name="dlSubtypes"),
    url(r'^(?P<id>\d+\.\d+\.\d+)/dlPerfect/$', 'hmmer.views.dlPerfect', name="dlPerfect"),
    url(r'^(?P<id>\d+\.\d+\.\d+)/dlShortnew/$', 'hmmer.views.dlShortnew', name="dlShortnew"),
    url(r'^(?P<id>\d+\.\d+\.\d+)/dlUnique/$', 'hmmer.views.dlUnique', name="dlUnique"),

    # multiples
    url(r'^(?P<id>\d+\.\d+\.\d+)/dlMultiples/$', 'hmmer.views.dlMultiples', name="dlMultiples"),
    ##url(r'^status/(?P<id>\d+\.\d+\.\d+)/(?P<dir>[A-I])/dlMultiples/$','hmmer.views.dlMultiples',name="dlMultiples"),

    # tree
    url(r'^(?P<id>\d+\.\d+\.\d+)/dlTree/$', 'hmmer.views.dlTree', name="dlTree"),
    ##url(r'^status/(?P<id>\d+\.\d+\.\d+)/(?P<dir>[A-I])/dlTree/$','hmmer.views.dlTree',name="dlTree"),

    # all
    url(r'^(?P<id>\d+\.\d+\.\d+)/dlEverything/$', 'hmmer.views.dlEverything', name="dlEverything"),
    # url(r'^status/(?P<id>\d+\.\d+\.\d+)/(?P<filename>[A-Z]+\_[a-z]+\.tsv)/download/$','hmmer.views.download',name="download"),
    url(r'^(?P<id>\d+\.\d+\.\d+)/dlBiom/$', 'hmmer.views.dlBiom', name="dlBiom"),

)

webUI/hmmer/models.py
from django.db import models
from django.contrib import admin



class symTyperTask(models.Model):
    NOT_STARTED = 0
    DONE = 1
    ERROR = 2
    RUNNING = 3
    STATES=  ( (NOT_STARTED, "Not Started",),
               (RUNNING, "Running",),
               (DONE, "Done",),
               (ERROR, "Error",),
             )

    celeryUID = models.TextField(null=True, blank=True)
    UID = models.TextField(null=True, blank=True)
    state = models.IntegerField(default = NOT_STARTED, choices = STATES, blank = False, null = False)
    modified = models.DateField(auto_now = True)
    created = models.DateField(auto_now_add = True)
    params = models.TextField(null = False, blank = False)

class AdminSymTyperTask(admin.ModelAdmin):
    list_display = ['celeryUID', 'UID', 'created', 'modified']


#admin.site.register(symTyperTask, AdminSymTyperTask)

webUI/hmmer/forms.py
import yaml
from django import forms

class InputForm(forms.Form):
    fasta_File = forms.FileField()
    sample_File = forms.FileField()
    clade_evalue = forms.FloatField(label = "E-Value", initial = 1e-20, )
    clade_evalDiff = forms.FloatField(label = "E-value Difference", initial = 1e5)
    subtype_evalue = forms.FloatField(label = "E-Value", initial = 1e-05, )
    resolveMulti_similarity = forms.FloatField(label = "Similarity", initial = 0.97, )


    def __init__(self, *args, **kwargs):
       super(InputForm, self).__init__(*args, **kwargs)
       self.fields['clade_evalue'].widget.attrs['readonly'] = True
       self.fields['clade_evalDiff'].widget.attrs['readonly'] = True
       self.fields['subtype_evalue'].widget.attrs['readonly'] = True
       self.fields['resolveMulti_similarity'].widget.attrs['readonly'] = True

    def clean_fasta_File(self):
        data = self.cleaned_data['fasta_File']
        if not data.name.endswith('.fasta'):
            raise forms.ValidationError("extension must be fasta")
        return data

    def clean_sample_File(self):
        data = self.cleaned_data['sample_File']
        if not data.name.endswith('.ids'):
            raise forms.ValidationError("extension must be ids")
        return data

    def yamlfyParams(self):
        """
        Currently, the dictionary keys are an encoding for the section and the field name.
        We replace all spaces with + and we use _ to seperate the section from the field.
        """

        return yaml.dump(
            { 'version_tag': 2,
              'order': ['clade', 'subtype', 'resolve multiplie hits'],
              'clade': {'e-value' : self.cleaned_data['clade_evalue'], 'e-value differences' : self.cleaned_data['clade_evalDiff']},
              'resolve multiplie hits': {'similarity' : self.cleaned_data['resolveMulti_similarity']},
              'subtype': {'e-value' : self.cleaned_data['subtype_evalue']}
              }
            )

#        return yaml.dump({ 'clade_e-value' : self.cleaned_data['clade_evalue'],
#          'clade_e-value+differences' : self.cleaned_data['clade_evalDiff'],
#          'resolve+multiplie+hits_similarity' : self.cleaned_data['resolveMulti_similarity'],
#          'subtype_e-value' : self.cleaned_data['subtype_evalue']})
 

webUI/hmmer/views.py
from django.template import RequestContext
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render_to_response
from django.shortcuts import render

from django.conf import settings
from django.core.urlresolvers import reverse
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

#from celery.result import AsyncResult

from general import writeFile, searchTable, csv2list, treeCsv, multiplesCsv, servFile, taskReady, servZip
from forms import InputForm
from models import  symTyperTask
from tasks import handleForm
from parse_hierarchy import parseHierarchyYAML


import os
import time
from collections import defaultdict
import yaml
# Create your views here.


def errorPage(request, template='upload.html'):
    return render(request, template)


def inputFormDisplay(request, template='upload.html'):
    """Displays input form that takes fasta and ids files."""
    if request.method == 'POST':
        form = InputForm(request.POST, request.FILES)
        if form.is_valid():
            # create UID
            sym_task = symTyperTask.objects.create()
            sym_task.UID = str(sym_task.id) + '.' + str(time.time())
            sym_task.params = form.yamlfyParams()
            sym_task.save()

            parentDir = os.path.join(settings.SYMTYPER_HOME, sym_task.UID)

            os.makedirs(parentDir)
            os.system("""chmod 775 %s"""%(parentDir))
            fasta = os.path.join(parentDir, "input.fasta")
            samples = os.path.join(parentDir, "samples.ids")

            writeFile(request.FILES['fasta_File'], fasta)
            writeFile(request.FILES['sample_File'], samples)

            task = handleForm.delay(fasta, samples, "test", sym_task.UID)
            return HttpResponseRedirect(reverse("index", args=[sym_task.UID]))
    else:
        form = InputForm()

    context = {'form': form,}

    return render(request, template, context)


def clades(request, id, template='clades.html'):
    """Displays clade results."""
    dirs = all_counts = detailed_counts = all_headers = detailed_headers = None

    try:
        sym_task = symTyperTask.objects.get(UID=id)
    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse("form"))

    output = os.path.join(settings.SYMTYPER_HOME, str(id), "hmmer_parsedOutput")
    ready, redirect = taskReady(sym_task)
    if ready:
        with open(os.path.join(output, "ALL_counts.tsv")) as tsv:
            # order is maintained and we don't really reorder, so why use zip and dict?
            all_headers = [ l for l in tsv.next().strip().split() ]
            all_counts = [ row.strip().split() for row in tsv ]

        with open(os.path.join(output, "DETAILED_counts.tsv")) as tsv:
            # remove the sample
            detailed_headers = tsv.next().strip().split()[1:]
            detailed_counts = [ zip(detailed_headers, row.strip().split()[1:]) for row in tsv ]

        paginator1 = Paginator(all_counts, 50)
        paginator2 = Paginator(detailed_counts, 50)

        page = request.GET.get('page')
        try:
            all_counts = paginator1.page(page)
            detailed_counts = paginator2.page(page)
        except PageNotAnInteger:
            all_counts = paginator1.page(1)
            detailed_counts = paginator2.page(1)
        except EmptyPage:
            all_counts_counts = paginator1.page(paginator.num_pages)
            detailed_counts = paginator2.page(paginator.num_pages)

    elif redirect:
        return redirect
    else:
        return HttpResponseRedirect(reverse("index", args=[sym_task.UID]))

    context = {
        'id': id,
        'title': "Clades",
        'dirs': dirs,
        'all_headers': all_headers,
        'all_counts': all_counts,
        'detailed_counts': detailed_counts,
        #'detailed_headers': detailed_headers,
    }

    return render(request, template, context)


##
# Subtypes
##

def unique(request, id, template='subtypes.html'):
    """Displays subtypes results."""

    try:
        sym_task = symTyperTask.objects.get(UID=id)
    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse("form"))

    output = os.path.join(settings.SYMTYPER_HOME, str(id), "blastResults")
    ready, redirect = taskReady(sym_task)
    if ready:
        counts, headers = csv2list(os.path.join(output, "UNIQUE_subtypes_count.tsv"))
        #shortnew_counts, shortnew_headers = csv2list(os.path.join(output, "SHORTNEW_subtypes_count.tsv"))
        #perfect_counts, perfect_headers = csv2list(os.path.join(output, "PERFECT_subtypes_count.tsv"))
    elif redirect:
        return redirect
    else:
        return HttpResponseRedirect(reverse("index", args=[sym_task.UID]))

    context = {
        #'shortnew_counts': shortnew_counts,
        #'shortnew_headers': shortnew_headers,
        #'unique_counts': unique_counts,
        #'unique_headers': unique_headers,
        #'perfect_counts': perfect_counts,
        #'perfect_headers': perfect_headers,
        'counts': counts,
        'headers': headers,
        'title': "Unique Subtypes",
        'id': id,
    }

    return render(request, template, context)


def shortnew(request, id, template='subtypes.html'):
    """Displays subtypes results."""

    try:
        sym_task = symTyperTask.objects.get(UID=id)
    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse("form"))

    output = os.path.join(settings.SYMTYPER_HOME, str(id), "blastResults")
    ready, redirect = taskReady(sym_task)
    if ready:
        counts, headers = csv2list(os.path.join(output, "SHORTNEW_subtypes_count.tsv"))
        #perfect_counts, perfect_headers = csv2list(os.path.join(output, "PERFECT_subtypes_count.tsv"))
    elif redirect:
        return redirect
    else:
        return HttpResponseRedirect(reverse("index", args=[sym_task.UID]))

    context = {
        'title': "Short New Subtypes",
        'counts': counts,
        'headers': headers,
        'id': id,
    }

    return render(request, template, context)


def perfect(request, id, template='subtypes.html'):
    """Displays subtypes results."""

    try:
        sym_task = symTyperTask.objects.get(UID=id)
    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse("form"))

    output = os.path.join(settings.SYMTYPER_HOME, str(id), "blastResults")
    ready, redirect = taskReady(sym_task)
    if ready:
        counts, headers = csv2list(os.path.join(output, "PERFECT_subtypes_count.tsv"))
    elif redirect:
        return redirect
    else:
        return HttpResponseRedirect(reverse("index", args=[sym_task.UID]))

    context = {
        'title': "Perfect Subtypes",
        'counts': counts,
        'headers': headers,
        'id': id,
    }

    return render(request, template, context)



def multiplesCorrected(request, id, file, template='multiples.html'):
    """Displays corrected multiples results."""

    try:
        sym_task = symTyperTask.objects.get(UID=id)
    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse("form"))

    corrected = os.path.join(settings.SYMTYPER_HOME, str(id), "resolveMultiples", "correctedMultiplesHits", "corrected")
    ready, redirect = taskReady(sym_task)
    if ready:
        corrected_counts, corrected_headers, corrected_breakdown, corrected_subtypes = multiplesCsv(os.path.join(corrected, file))

        if corrected_counts != None and corrected_subtypes != None and corrected_breakdown != None:
            paginator1 = Paginator(corrected_counts, 5)
            paginator2 = Paginator(corrected_breakdown, 5)
            paginator3 = Paginator(corrected_subtypes, 5)

            page = request.GET.get('page')
            try:
                counts = paginator1.page(page)
                breakdown = paginator2.page(page)
                subtypes = paginator3.page(page)
            except PageNotAnInteger:
                counts = paginator1.page(1)
                breakdown = paginator2.page(1)
                subtypes = paginator3.page(1)
            except EmptyPage:
                counts = paginator1.page(paginator.num_pages)
                breakdown = paginator2.page(paginator.num_pages)
                subtypes = paginator3.page(paginator.num_pages)

    elif redirect:
        return redirect
    else:
        return HttpResponseRedirect(reverse("status", args=[sym_task.UID]))

    context = {
        'counts': counts,
        'headers': corrected_headers,
        'breakdown': breakdown,
        'subtypes': subtypes,
        'id': id,
        'file': file,
    }

    return render(request, template, context)


def multiplesResolved(request, id, file, template='multiples.html'):
    """Displays resolved multiples results."""

    try:
        sym_task = symTyperTask.objects.get(UID=id)
    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse("form"))

    resolved = os.path.join(settings.SYMTYPER_HOME, str(id), "resolveMultiples", "correctedMultiplesHits", "resolved")
    ready, redirect = taskReady(sym_task)
    if ready:

        resolved_counts, resolved_headers, resolved_breakdown, resolved_subtypes = multiplesCsv(os.path.join(resolved, file))

        if resolved_counts != None and resolved_subtypes != None  and resolved_breakdown != None:
            paginator1 = Paginator(resolved_counts, 5)
            paginator2 = Paginator(resolved_breakdown, 5)
            paginator3 = Paginator(resolved_subtypes, 5)

            page = request.GET.get('page')
            try:
                counts = paginator1.page(page)
                breakdown = paginator2.page(page)
                subtypes = paginator3.page(page)
            except PageNotAnInteger:
                counts = paginator1.page(1)
                breakdown = paginator2.page(1)
                subtypes = paginator3.page(1)
            except EmptyPage:
                counts = paginator1.page(paginator.num_pages)

webUI/hmmer/templates/biom_graph.html
{% extends "base.html" %}
{% load custom_filters %}

{% block head %}
<title>Breakdown - Sample: {{sample}}</title>
<script src="http://d3js.org/d3.v3.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:400,600" />
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/sequences.css"/>
{% endblock %}

{% block body %}
<div class="container" id = "container_1">
  <div id="main_1" class="main">
    <div id="sequence_1" class="sequence" ></div>
    <div id="chart_1" class="chart"></div>
    <div id="explanation_1" class="explanation" style= "visibility: hidden" ><span class="percentage" id="percentage_1"></span> <br /> of sample {{sample}}</div>
  </div>
  <ul  class="nav navbar-nav">
    <li class = "dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Compare to<b class="caret"></b></a>
      <ul class = "dropdown-menu">
	{% for k in sampleids %}
	{% if k != sample %}
	<li><a href="{% url 'biomburst_sxs' id sample k %}">{{sample}} vs. {{ k }}</a></li>
	{% endif %}
	{% endfor %}
      </ul>
    </li>
  </ul>
  <div id="sidebar_1" class="sidebar">
    <div id="legend_1" class="legend" {# style="visibility: hidden;"#}></div>
  </div>
</div>


<script type="text/javascript" src="{{ STATIC_URL }}/js/sequences.min.js"></script>
<script type="text/javascript">
  d3.json( '{% url 'json_biomburst' uid=uid sample=sample %}', function(error, json) {
  if (error){return console.warn(error);}
  var bb, clr, li;
  bb = { w: 140, h: 30, s: 3, t: 10};
  clr = json[1];
  //Dimensions of legend item: width, height, spacing, radius of rounded rect.
  li = {w: 190, h: 30, s: 3, r: 3};  
  graph1 = new Sun_Burst(950, 900, bb , clr, 1);
  graph1.createVisualization(json[0], li)
  {#setVars(950, 900, bb , clr);#}
  //createVisualization(json[0]);
  });
</script>


{% endblock %}

webUI/hmmer/templates/chart.html
{% extends "base.html" %}
{% load custom_filters %}

{% block body %}
<div id="chart_div_{{ site }}"></div>

<script type="text/javascript">

// Load the Visualization API and the piechart package.
google.load('visualization', '1.0', {'packages':['corechart'],"callback":drawChart});

// Set a callback to run when the Google Visualization API is loaded.
//google.setOnLoadCallback(drawChart);

function drawChart() {

    // Create the data table.
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'clade'); 
    data.addColumn('number', 'amount'); 
    data.addRows([
            {% for key, value in detailed_counts.items %} 
            ['{{ key }}',{{ value }}],
            {% endfor %}
            ]);

    // Set chart options
    var options = {
        'backgroundColor': 'transparent',
        'width':400,
        'height':300};

    // Instantiate and draw our chart, passing in some options.
    var chart = new google.visualization.PieChart(document.getElementById('chart_div_{{ site }}'));
    chart.draw(data, options);
}
</script>
{% endblock %}

webUI/hmmer/templates/upload.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block head %}
<title>File Form</title>
{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-7">
	  <div class = "well">
	  <h4>Sample Data</h4>
	  <div >
	    <ul><li><a href = "{{ STATIC_URL }}sample/sample.fasta">Sample Fasta</a></li><li><a href = "{{ STATIC_URL }}sample/sample.ids">Sample IDs</a></li></ul>
	  </div>
	  </div>
          <div class="well"> 

	      <div class="col-md-12">
	
                    <form role="form" enctype="multipart/form-data" method="post" action=".">

                        <div class="form-group{% if form.fasta_File.errors %} has-error{% endif %}">
                            <label for="id_fasta_File">Fasta File </label>
                            <span class="info glyphicon glyphicon-info-sign pull-right" data-content="Valid Fasta format in which the sequence IDs match those found in the id file" data-placement="top" data-toggle="popover" data-trigger="hover"></span>

                            {{ form.fasta_File }}

                            {% if form.fasta_File.errors %}
                            <span class="help-block">
                                <ol>
                                    {% for error in form.fasta_File.errors %}
                                    <li><strong> {{ error|escape }} </strong></li>
                                    {% endfor %}
                                </ol>
                            </span>
                            {% endif %}
                        </div>

                        <div class="form-group{% if form.sample_File.errors %} has-error{% endif %}">
                            <label for="id_sample_File">Id File </label>
                            <span class="info glyphicon glyphicon-info-sign pull-right" data-content="A listing of sample ids" data-placement="top" data-toggle="popover" data-trigger="hover"></span>

                            {{ form.sample_File }}

                            {% if form.sample_File.errors %}
                            <span class="help-block">
                                <ol>
                                    {% for error in form.sample_File.errors %}
                                    <li><strong> {{ error|escape }} </strong></li>
                                    {% endfor %}
                                </ol>
                            </span>
                            {% endif %}

                        </div>

			<fieldset>
			  <legend>Clade:</legend>
                       <div class="form-group{% if form.clade_evalue.errors %} has-error{% endif %}">
                            <label for="clade_e_value">E-value </label>
                            <span class="info glyphicon glyphicon-info-sign pull-right" data-content="E-value utilized by blast" data-placement="top" data-toggle="popover" data-trigger="hover"></span>
			    {{form.clade_evalue}}
                        </div>
                        <div class="form-group{% if form.clade_evalDiff.errors %} has-error{% endif %}">
                            <label for="clade_e_valueDiff">E-value Difference</label>
                            <span class="info glyphicon glyphicon-info-sign pull-right" data-content="?????" data-placement="top" data-toggle="popover" data-trigger="hover"></span>
			    {{form.clade_evalDiff}}
                        </div>
			</fieldset>

			<fieldset>
			  <legend>Subtype:</legend>
			  <div class="form-group{% if form.subtype_evalue.errors %} has-error{% endif %}">
                            <label for="subtype_evalue">E-value</label>
                            <span class="info glyphicon glyphicon-info-sign pull-right" data-content="?????" data-placement="top" data-toggle="popover" data-trigger="hover"></span>
			    {{form.subtype_evalue}}
                          </div>
			</fieldset>

			<fieldset>
			  <legend>Resolve Multiple Hits:</legend>
                        <div class="form-group{% if form.resolveMulti_similarity.errors %} has-error{% endif %}">
                            <label for="resolveMulti_similarity">Similarity</label>
                            <span class="info glyphicon glyphicon-info-sign pull-right" data-content="?????" data-placement="top" data-toggle="popover" data-trigger="hover"></span>
			    {{form.resolveMulti_similarity}}
                        </div>


                        <button class="btn btn-default" type="submit">Submit</button>
                        {% csrf_token %}
                    </form>
                </div>
            </div>
        </div>

        <div class="col-md-5">
            <div class="well">
                <h2>About Symtyper</h2>
                <p><a href="">View preprint manuscript</a></p>
		<hr />
		The current version of the SymTyper Symbiodinium database is:<br/ ><b>2014-02-12</b>. The clade composition is:<br />
		  
		<table class ="table-bordered table-condensed" >
		  <tr><td>Clade</td><td>Numer of sequences</td></tr>
		  <tr><td>A</td><td>81</td></tr>
		  <tr><td>B</td><td>34</td></tr>
		  <tr><td>C</td><td>465</td></tr>
		  <tr><td>D</td><td>44</td></tr>
		  <tr><td>E</td><td>16</td></tr>
		  <tr><td>F</td><td>54</td></tr>
		  <tr><td>G</td><td>9</td></tr>
		  <tr><td>H</td><td>12</td></tr>
		  <tr><td>I</td><td>4</td></tr>
		</table>

		<a href = "">Download database</a>
		<hr />
		<br />
                <div class="row">
                    <div class="col-lg-6">
                        <div class="input-group">
                            <input type="text" placeholder="112.1382325231.99" class="form-control">
                            <span class="input-group-btn">
                                <button class="btn btn-primary" type="button">Go!</button>
                            </span>
                        </div><!-- /input-group -->
                    </div><!-- /.col-lg-6 -->
                </div>
            </div>
        </div>

    </div>
</div>

<script type="text/javascript">
    $('.info').popover()
</script>


<!--<script type="text/javascript">-->
    <!--$(document)-->
    <!--.on('change', '.btn-file :file', function() {-->
            <!--var input = $(this),-->
            <!--numFiles = input.get(0).files ? input.get(0).files.length : 1,-->
            <!--label = input.val().replace(/\\/g, '/').replace(/.*\//, '');-->
            <!--input.trigger('fileselect', [numFiles, label]);-->
            <!--});-->
    <!--$(document).ready( function() {-->
            <!--$('.btn-file :file').on('fileselect', function(event, numFiles, label) {-->
                <!--var input = $(this).parents('.input-group').find(':text'),-->
                <!--log = numFiles > 1 ? numFiles + ' files selected' : label;-->
                <!--if( input.length ) {-->
                <!--input.val(log);-->
                <!--} else {-->
                <!--if( log ) alert(log);-->
                <!--}-->
                <!--});-->
            <!--}); -->
    <!--</script>-->

{% endblock %}